name: Ryan Emerson
markdown: kramdown
theme: jekyll-theme-time-machine
title: Ryan Emerson's Collection of things! 
description: This is a little respository for Data Science projects and coding that I put together. Hopefully all referenced properly! 
